//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Group = new HashSet<Group>();
            this.Positions = new HashSet<Position>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Site { get; set; }
        public string Mail { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<Position> Positions { get; set; }
        public virtual ICollection<Emploee> Employee { get; set; }
        public virtual User User { get; set; }
    }
}
