//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterionCategory
    {
        public CriterionCategory()
        {
            this.CriteriaCategories = new HashSet<CriterionCategory>();
            this.Criterion = new HashSet<Criterion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ICollection<CriterionCategory> CriteriaCategories { get; set; }
        public virtual CriterionCategory CriteriaCategory1 { get; set; }
        public virtual ICollection<Criterion> Criterion { get; set; }
    }
}
