//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterion
    {
        public Criterion()
        {
            this.CriterionValues = new HashSet<CriterionValues>();
            this.CreterionTest = new HashSet<CreterionTest>();
            this.EmploeeCriterion = new HashSet<EmploeeCriterion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public int TypeId { get; set; }
    
        public virtual CriterionCategory CriteriaCategories { get; set; }
        public virtual CriterionType CriterionTypes { get; set; }
        public virtual ICollection<CriterionValues> CriterionValues { get; set; }
        public virtual ICollection<CreterionTest> CreterionTest { get; set; }
        public virtual ICollection<EmploeeCriterion> EmploeeCriterion { get; set; }
    }
}
