//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploee
    {
        public Emploee()
        {
            this.EmploeeCriterion = new HashSet<EmploeeCriterion>();
            this.EmploeeGroup = new HashSet<EmploeeGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<EmploeeCriterion> EmploeeCriterion { get; set; }
        public virtual ICollection<EmploeeGroup> EmploeeGroup { get; set; }
    }
}
