//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploeeGroup
    {
        public int Id { get; set; }
        public int EmploeeId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Groups { get; set; }
        public virtual Emploee Emploees { get; set; }
    }
}
