//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Criterion> Criteria { get; set; }
        public virtual DbSet<CriterionCategory> CriterionCategories { get; set; }
        public virtual DbSet<CriterionValues> CriterionValues { get; set; }
        public virtual DbSet<CriterionType> CriterionTypes1 { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestValue> TestValues { get; set; }
        public virtual DbSet<TestType> TestTypes { get; set; }
        public virtual DbSet<TestItem> TestItems { get; set; }
        public virtual DbSet<CreterionTest> CreterionTests { get; set; }
        public virtual DbSet<Emploee> Emploees { get; set; }
        public virtual DbSet<EmploeeCriterion> EmploeeCriterions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<EmploeeGroup> EmploeeGroups { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
    }
}
