//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestValue
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int TestItemId { get; set; }
        public string Sort { get; set; }
    
        public virtual TestItem TestItem { get; set; }
    }
}
