//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestItem
    {
        public TestItem()
        {
            this.TestValues = new HashSet<TestValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TestId { get; set; }
        public string Sort { get; set; }
    
        public virtual Test Tests { get; set; }
        public virtual ICollection<TestValue> TestValues { get; set; }
    }
}
