//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.TestItem = new HashSet<TestItem>();
            this.CreterionTests = new HashSet<CreterionTest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TypeId { get; set; }
    
        public virtual TestType TestTypes { get; set; }
        public virtual ICollection<TestItem> TestItem { get; set; }
        public virtual ICollection<CreterionTest> CreterionTests { get; set; }
    }
}
