//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreterionTest
    {
        public int Id { get; set; }
        public int CriterionId { get; set; }
        public int TestId { get; set; }
    
        public virtual Criterion Criteria { get; set; }
        public virtual Test Test { get; set; }
    }
}
