//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploeePosition
    {
        public int Id { get; set; }
        public int EmploeeId { get; set; }
        public int PositionId { get; set; }
    
        public virtual Emploee Emploee { get; set; }
        public virtual Position Positions { get; set; }
    }
}
