//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Criterion> Criteria { get; set; }
        public virtual DbSet<CriterionCategory> CriterionCategories { get; set; }
        public virtual DbSet<CriterionValues> CriterionValues { get; set; }
        public virtual DbSet<CriterionType> CriterionTypes1 { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestValue> TestValues { get; set; }
        public virtual DbSet<TestType> TestTypes { get; set; }
        public virtual DbSet<TestItem> TestItems { get; set; }
        public virtual DbSet<CreterionTest> CreterionTests { get; set; }
        public virtual DbSet<Emploee> Emploees { get; set; }
        public virtual DbSet<EmploeeCriterion> EmploeeCriterions { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<EmploeeGroup> EmploeeGroups { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<EmploeePosition> EmploeePositions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
