//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.TestItem = new HashSet<TestItem>();
            this.CreterionTests = new HashSet<CreterionTest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TypeId { get; set; }
    
        public virtual TestType TestTypes { get; set; }
        public virtual ICollection<TestItem> TestItem { get; set; }
        public virtual ICollection<CreterionTest> CreterionTests { get; set; }
    }
}
