//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAPP.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestItem
    {
        public TestItem()
        {
            this.TestValues = new HashSet<TestValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TestId { get; set; }
        public string Sort { get; set; }
    
        public virtual Test Tests { get; set; }
        public virtual ICollection<TestValue> TestValues { get; set; }
    }
}
